[tools]
node = "latest"
go = "latest"
kubectl = "latest"
helm = "latest"
minikube = "latest"
kubectx = "latest"
# kubens = "latest"
k9s = "latest"

[alias]
kubectx = "https://gitlab.com/wt0f/asdf-kubectx"
kubectl = "https://github.com/asdf-community/asdf-kubectl"